In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [52]:
df = pd.read_csv("play_tennis.csv")

In [53]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [54]:
df = df.drop(['day'], axis=1)

In [55]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [56]:
df.isnull().sum()

outlook     0
temp        0
humidity    0
wind        0
play        0
dtype: int64

In [57]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [58]:
PYes = 9/14
PNo = 5/14

In [59]:
pd.crosstab(df['outlook'], df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [60]:
POvercastNo = 0
PRainNo = 2/5
PSunnyNo = 3/5

POvercastYes = 4/9
PRainYes = 3/9
PSunnyYes = 2/9

In [61]:
pd.crosstab(df['temp'], df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [62]:
PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5

PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [63]:
pd.crosstab(df['humidity'], df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [64]:
PHighNo = 4/5
PNormalNo = 1/5

PHighYes = 3/9
PNormalYes = 6/9

In [65]:
pd.crosstab(df['wind'], df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [66]:
PStrongNo = 3/5
PWeakNo = 2/5

PStrongYes = 3/9
PWeakYes = 6/9

In [71]:
#Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak

Pyes= PSunnyYes * PHotYes * PHighYes * PWeakYes * PYes
Pno= PSunnyNo * PHotNo * PHighNo * PWeakNo * PNo

In [72]:
Pyes

0.007054673721340387

In [73]:
Pno

0.02742857142857143

In [74]:
#Answer = No Play